version: '3.9'

services:
  app:
    container_name: spacial_probe_ruby
    build:
      context: .
      dockerfile: .devops/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/app
